### ISSUE TITLE
Syntax Highlighting for Jupyter

### ISSUE THREAD

**Issue by merqurio** [jupyter/design#14]
Hi all, 

I'm aware you are working in a new theme as of #10 and I think it looks great, but you are not (at least from what I read) giving the user the possibility of choosing a specific syntax highlighting. Most IDE let the user choose from a variety of them. 

I think both things should be separated, as some user might not want to change the appearance of the notebook but only the highlighting. 

As in my university, teachers wanted to have a different syntax highlighting for the code so it could be easily disguised from text for those who are learning to code with Jupyter. I already created a plugin to do [this](https://github.com/merqurio/jupyter_themes), but it would be great to be integrated in the default package. 

What do you think about this ?

**Comment by Carreau** [comment]
Well, if we want to keep flexibility of highlighting/themening; and not reinvent the wheel, 
the highlighting should not be changed by injecting CSS like that actually.
CodeMirror have it's [owe way](https://codemirror.net/demo/theme.html) of changing syntax highlight, (which does use CSS, and yes it would be nice to do dynamic loading).  But it's more a config option that need to be changed.  

Also as far as I can tell, most of the css you overwrite (which are not codemirror) are variable in our `.less` files. So as I pointed in jupyter/notebook#119 should be provided by a custom variable.less file and should "just" have to be recompiled. Otherwise as soon as we change the class and structure of the notebook, theses will get out of sync, and we'll get bug reports.

If some of theses are not variables (I guess the ansi code won't be) then they should be.

We'll be mostly happy to get the right hook in IPython to make that easier, but we just need the man power and caring people to work on that.

(also the colorscheme persistence should be hook into our frontend config system which is mostly undocumented)

**Comment by merqurio** [comment]
If codemirror has it's own way of loading css for highlighting I wouldn't reinvent the wheel and I would try to get that option working on the front-end so users can happily change those highlighting and store their preferences at the front-end config system.

I know that in my implementation there are some classes outside the codemirror that are modified, but I don't find those really necessary, do you ?

I've experience with JS, so I would gladly work on that. Any suggestion on how and where shoul implement that ? That way I can do a PR

Thanks for your time

**Comment by neilpanchal** [comment]
@merqurio @Carreau I like the idea of enabling the end user to specify the theme (not just colors, but fonts too) similar to how Google's prettify.js does it. I personally think we need to develop a roadmap for a full featured browser based IDE (where color themes are just one of the many taken-as-granted features of any modern IDE). We are far from that vision.

**Comment by Carreau** [comment]
> I know that in my implementation there are some classes outside the codemirror that are modified, but I don't find those really necessary, do you ?

No agreed, we can slowly work on that. 

> I've experience with JS, so I would gladly work on that. Any suggestion on how and where shoul implement that ? That way I can do a PR

On jupyter/notebook repo. Feel free to even send an early draft PR. Even if at the beginning it's just API like `IPython/set_codemirrior_theme('themename')` its fine.

> I like the idea of enabling the end user to specify the theme (not just colors, but fonts too) similar to how Google's prettify.js does it.

The full coloring is slightly  more complicated as people display custom html/css graph in the notebook. And typically you want theses to match. (Problem you don't have with IDEs) 

> I personally think we need to develop a roadmap for a full featured browser based IDE (where color themes are just one of the many taken-as-granted features of any modern IDE). We are far from that vision.

It's on the roadmap, but far. Rodeo is an in browser IDE that rely on our protocol. We like composability, and we are more focus on language agnosticity right now. And as I said, we fine with working on theme, but none of us have the bandwidth.

**Comment by merqurio** [comment]
I [updated the plugin,](https://github.com/merqurio/jupyter_themes/blob/master/theme_selector.js#L104) now it uses the CodeMirror API and Jupyter nbextension to store default value. Would this be more appropriate for an PR ?

**Comment by Carreau** [comment]
I think it is fine to keep it as a plugin, but @ijstokes is [discussing](https://github.com/jupyter/jupyter/issues/124) a few default extension that would be integrated by default into the notebook with anaconda (and with 4.2/4.3 instead of waiting for 5.0. That would be a nice intermediate step to flush out last issues, and potentially integrate that on next iteration
